### ISSUE TITLE
popping up exit status 1

### ISSUE THREAD

**Issue by sri123098** [ckshitij/LEX#4]
Hi ,
When I tried to execute this one, I'm getting the following error.
/tmp/8136022.1.h/ccPKPckp.o: In function `yyparse':
y.tab.c:(.text+0x422): undefined reference to `pow'
collect2: ld returned 1 exit status

Could you please help me with this issue?

Thanks,
Sriram

**Comment by ckshitij** [comment]
Are facing problem In Calculator?
If yes please Attach the ScreenShot.
